# Generated by Django 3.0.2 on 2020-09-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
