# Generated by Django 3.0.2 on 2020-09-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_auto_20200923_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='charges',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='creditorBalance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='debtorBalance',
            field=models.FloatField(default=0),
        ),
    ]
