# Generated by Django 3.0.2 on 2020-09-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_auto_20200923_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, choices=[('deposit', 'deposit')], max_length=1000, null=True),
        ),
    ]
